service:
  server:
    id: webhook_bridge_service
    hash: wbs_hash
    logger:
      logs_path: /path/to/webhook-bridge-service/logs/
      error_log_file: error.log
      combined_log_file: combined.log
    port: 9000
  services:
    example:
      push_urls:
        - example.com/push
      branch: master
      # tag: true
      hash: default_hash
